[package]
name = 'aux'
version = '1.0.0'

[addresses]
aux = '_'
#'0x3e667f6acf56a4dab28bbfdb3badcbb77fdc260b9504cbcce2392badf6830d5b'
#deployer = '_'

#[dev-addresses]
## this address is the resource account from 0x5E7C3 and seed amm
## go run ./go-util/aptos/cmd/calculate-resource-address -a 0x5E7C3 - s amm
#aux = '0x3e667f6acf56a4dab28bbfdb3badcbb77fdc260b9504cbcce2392badf6830d5b'
##deployer = '0x8686'

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = '0377a5f9825110c63b741b0a6d735ff6b4f945b7'
subdir = 'aptos-move/framework/aptos-framework'

#[dependencies.deployer]
#local = '../deployer'
